### ISSUE TITLE
www.-prefix stops xqemu.com from working

### ISSUE THREAD

**Issue by JayFoxRox** [xqemu/xqemu.com#10]
When typing "xqemu.com" into the Firefox addressbar, it will autocomplete to "www.xqemu.com" (added "www.").
However, going to "http://www.xqemu.com" or "https://www.xqemu.com" will fail (due to "www."):

**"We can’t connect to the server at www.xqemu.com."**

This message is very misleading.

If anyone wants to visit our website currently, they have to explicitly type "http://xqemu.com" or "https://xqemu.com" (without "www."). This should be fixed.

**Comment by CakeLancelot** [comment]
This should be fixed with a CNAME record in the DNS. Just create one and point www.xqemu.com to xqemu.com, you *may* have some trouble with HTTPS because of the different subdomains but don't quote me on that.

**Comment by GXTX** [comment]
SSL would be a problem unless the cert has an alt-name to cover www.xqemu.com & xqemu.com.

**Comment by CakeLancelot** [comment]
Well, at least let's  encrypt does wildcard certs

**Comment by espes** [comment]
At some point google domains added ssl http forwarding and I enabled it a while ago
