### ISSUE TITLE
Operating-system order in documentation is inconsistent

### ISSUE THREAD

**Issue by JayFoxRox** [xqemu/xqemu.com#11]
The order of the sections is always changing. Sometimes it's [macOS, Windows, Linux](https://xqemu.com/getting-started/#building-xqemu-from-source) and other times it's [Linux, Windows](https://xqemu.com/networking/).

We should avoid such inconsistency and list them in order of importance:

- Windows (most users)
- macOS (some users)
- Linux (very few users)

*I'd also suggest to add some `<spoiler>`-like tags or identification icons so users can find their OS more quickly ([See my experiments with this on OpenSWE1R](https://github.com/OpenSWE1R/openswe1r/wiki/Build-Instructions)).*

**Comment by mborgerson** [comment]
Fixed
