### ISSUE TITLE
"Getting Started" refers to `qemu-img` which is not part of `build.sh` compilation

### ISSUE THREAD

**Issue by JayFoxRox** [xqemu/xqemu.com#19]
This also affects `i386-softmmu/qemu-system-i386` which only exists after installation.

We should clarify that the user needs QEMU installed already. Ideally also refer to a download page for QEMU.

Alternatively we could package the `qemu-img` binary with our XQEMU CI release, and mention `xqemu` instead of `i386-softmmu/qemu-system-i386` (and we'll have to make sure we don't break compatibility with these tools). We would also have to mention that XQEMU needs to be compiled first for users of the source-version.

**Comment by CakeLancelot** [comment]
I believe this has been removed when the pre-built image option was added, as I can't find any mention of it now.

**Comment by JayFoxRox** [comment]
Yes. Closed in https://github.com/xqemu/xqemu.com/commit/9c561c07f25844e2f8944d941901e3a77678af95
