### ISSUE TITLE
Developer page does not link to GitHub

### ISSUE THREAD

**Issue by JayFoxRox** [xqemu/xqemu.com#25]
The developers tab should provide info how to reach us and how to get started with development. Related to https://github.com/xqemu/xqemu/issues/46 (and possibly linked issues).

I know that we have a GitHub link in the header, but I think we should still provide it again, for visibility.

**Comment by CakeLancelot** [comment]
I think the problem in the title has been fixed?
![image](https://user-images.githubusercontent.com/5341136/51919983-1d083380-23aa-11e9-9086-fb5fd42bf366.png)
Though, the developer page should be expanded upon as you said. Perhaps rename the issue?

**Comment by JayFoxRox** [comment]
Yes. Closed in https://github.com/xqemu/xqemu.com/commit/3905efd03295f6207d6cfaf515af8c0d25c125a0
