### ISSUE TITLE
Add link on Screenshots page to album at xqemu.imgur.com

### ISSUE THREAD

**Issue by mborgerson** [xqemu/xqemu.com#28]
I totally forgot we had this album on Imgur: https://xqemu.imgur.com/

We should link to it on the screenshots page. Although, it needs some updating. Rendering in some games has improved dramatically (THPS2X for instance).

**Comment by JayFoxRox** [comment]
Let's consider the imgur album a 1.0 artifact.

It should be registered to my email address and we should be able to recover it, if we ever feel like it.
For now, I'll close this. We have some more recent media on the website now.
