### ISSUE TITLE
"Building XQEMU from Source" should be a developer article

### ISSUE THREAD

**Issue by JayFoxRox** [xqemu/xqemu.com#30]
This is currently in Getting Started (which is aimed at users) https://xqemu.com/getting-started/#building-xqemu-from-source

**Comment by JayFoxRox** [comment]
This might even apply to "Running XQEMU" and other sections of the website: With XQEMU-Manager, these sections become part of the internal interfaces. Only developers of GUI frontends should care about them.

We can also safely assume that users aren't using a CLI.

**Comment by mborgerson** [comment]
Closed by #35
