### ISSUE TITLE
XQEMU.com Getting Started Instructions for Linux are off.

### ISSUE THREAD

**Issue by CYRiXplaysHalo** [xqemu/xqemu.com#31]
https://xqemu.com/getting-started/#building-on-gnulinux

When trying to follow the first instruction for building on GNU/Linux using the same distro (Ubuntu 18.04):

First enable deb-src via:

    sudo gedit /etc/apt/sources.list

In this file, uncomment first deb-src line.

I can't find any line in the sources.list file that starts with "deb-src". We should probably rephrase this to at least say what the line is so that people can just add it in themselves if their linux install doesn't already have it commented out.

**Comment by JayFoxRox** [comment]
Just a small note:

This has moved to the developer section; https://github.com/xqemu/xqemu.com/blob/5253cdf4604eebae5e4d5ca652e42a6806fa7b06/docs/developers/building.md

The documentation wasn't changed? So this is still a valid issue probably.
