### ISSUE TITLE
Top menu never reappears after scrolling down

### ISSUE THREAD

**Issue by JayFoxRox** [xqemu/xqemu.com#40]
If I scroll down, the top menu with "Welcome" and "Developers" will disappear.

When I scroll up, it never re-appears.

The only exception where it reappears is the first page "Welcome" (https://xqemu.com). It also disappears on the "Developers" page (https://xqemu.com/developers/) which makes it hard to switch back to the user portion of the website.

**Comment by mborgerson** [comment]
I'm having trouble reproducing this. Which browser are you using?

**Comment by JayFoxRox** [comment]
FireFox 66.0.5 (64-bit) on Arch Linux

**Before scrolling:**

![before](https://user-images.githubusercontent.com/360330/58301000-1da75880-7de5-11e9-8e3c-2eaff5362cb7.png)

**After scrolling down, and back up**

![after](https://user-images.githubusercontent.com/360330/58301006-2009b280-7de5-11e9-82c3-5ab9608fb033.png)

---

I'll try to reproduce in another user-profile or another machine soon. I believe this issue has always existed for me.

**Comment by dracc** [comment]
Firefox 67.0 on Windows 10 here, can't reproduce.

**Comment by JayFoxRox** [comment]
It seems to be related to fonts / font-sizes / zoom-levels.

- I can fix it by setting zoom to ~90% or smaller.
- On Linux, I can reproduce it by setting `font.size.variable.x-western` to 14 instead of the default (would be 16) in FireFox `about:config`.
- On Windows, I was unable to reproduce it like this.

This font-size setting is also available through the GUIs and should not affect the design.

I assume it works on the main page, because there's an additional "XQEMU is an open-source emulator to play original Xbox games on Windows, macOS, and Linux." banner, which probably adds some offsets to this coordinate logic.

This is an upstream problem in https://github.com/squidfunk/mkdocs-material and also happens on the example website.
No GitHub issue exists yet. I'll create one, linking to this discussion.

**Comment by JayFoxRox** [comment]
Fixed in squidfunk/mkdocs-material 4.4.0 (see linked issue from previous post).

I've triggered a re-build on https://travis-ci.org/xqemu/xqemu.com/builds/543901441 and that solved this issue.

Closed.
