### ISSUE TITLE
Developer "Welcome" page AppVeyor badge links to non-master branch

### ISSUE THREAD

**Issue by JayFoxRox** [xqemu/xqemu.com#44]
The badge appears to display the status of the master branch, but it actually links to the last build (including PRs). This is confusing and might lead to people downloading wrong code / binaries.

The link and badge should both point at the master branch.

*(I did not check if this is also an issue for Travis)*

**Comment by dracc** [comment]
https://github.com/xqemu/xqemu/commit/27bb1155e5aeb70e94b949dca6848336f5f09cfc might be worth using as reference.
